bot:
  guild:
    ticket-category-id: '896872221618896956'
    ticket-chat-id: '896872174940463166'
    id: '896553346738057226'
    logs-chat-id: '967796676242841781'
    ticket:
      title: ':telephone: Atendimento da RealHosting'
      footer: Atendimento oficial da RealHosting
      description: Seja bem-vindo(a) ao atendimento da RealHosting. Para iniciar seu
        atendimento selecione a categoria no meu abaixo.
      thumbnail: https://media.discordapp.net/attachments/856621081438453770/1027391598541164574/Dois_Laranjas.png?width=534&height=534
      site: https://app.realhosting.com.br
      fields:
        '1':
          name: Horário de Atendimento
          value: 14:30 às 23:00
          inline: true
        '2':
          name: Dias de Atendimento
          value: Segunda a Sexta (Salvo Feriados)
          inline: true
    close-ticket:
      title: ':x: Você quer fechar este ticket?'
      footer: Atendimento oficial da RealHosting
      thumbnail: https://media.discordapp.net/attachments/856621081438453770/1027391598541164574/Dois_Laranjas.png?width=534&height=534
      description: Clique no botão vermelho para fechar este ticket!
      site: https://app.realhosting.com.br
      fields:
        '1':
          name: Horário de Atendimento
          value: 14:30 às 23:00
          inline: true
        '2':
          name: Dias de Atendimento
          value: Segunda a Sexta (Salvo Feriados)
          inline: true
    payment:
      title: ':desktop: Aqui você poderá escolher seu plano'
      footer: Auto-Atendimento oficial da RealHosting
      thumbnail: https://media.discordapp.net/attachments/856621081438453770/1027391598541164574/Dois_Laranjas.png?width=534&height=534
      description: Clique no plano que mais lhe agrada e veja a mágica acontecer!
      site: https://app.realhosting.com.br
      fields:
        '1':
          name: Horário de Atendimento
          value: 14:30 às 23:00
          inline: true
        '2':
          name: Dias de Atendimento
          value: Segunda a Sexta (Salvo Feriados)
          inline: true
      plans:
        '1':
          name: 'R$ 2,50 : 1GB + 1 Núcleo(s) | BASIC'
          value: bot.guild.payment.plans.1
          description: O plano para quem quer fazer pequenos testes.
          logo: https://cdn.discordapp.com/attachments/967481970797985822/1032005392357654619/Cinza.png
          id: '1'
          emoji: U+1FA99
        '2':
          name: 'R$ 5,00 : 2GB + 1 Núcleo(s) | MEDIAN'
          value: bot.guild.payment.plans.2
          description: O plano para quem quer jogar com amigos.
          logo: https://cdn.discordapp.com/attachments/967481970797985822/1032005392357654619/Cinza.png
          id: '2'
          emoji: U+1F4B5
        '3':
          name: 'R$ 10,00 : 4GB + 2 Núcleo(s) | ADVANCED'
          value: bot.guild.payment.plans.3
          description: O plano para quem quer fazer um pequeno servidor.
          logo: https://cdn.discordapp.com/attachments/967481970797985822/1032005393934725130/Azul_Escuro.png
          id: '3'
          emoji: U+1F4B2
        '4':
          name: 'R$ 20,00 : 8GB + 4 Núcleo(s) | MEGA'
          value: bot.guild.payment.plans.4
          description: O plano para quem quer fazer um servidor com plugins.
          logo: https://cdn.discordapp.com/attachments/967481970797985822/1032005393364287538/Dois_Larankas.png
          id: '4'
          emoji: U+1F4B0
        '5':
          name: 'R$ 40,00 : 16GB + 6 Núcleo(s) | ULTRA'
          value: bot.guild.payment.plans.5
          description: O plano para quem quer fazer uma rede de servidores.
          logo: https://cdn.discordapp.com/attachments/967481970797985822/1032005392907112488/Dois_Laranjas.png
          id: '5'
          emoji: U+1F48E
    pre-expiration:
      title: ':warning: Aviso de Vencimento de Plano'
      footer: Atendimento oficial da RealHosting
      description: 'Opa! Gostaria de avisá-lo, que, seu plano na RealHosting estará
        sendo suspenso em um dia. Para seu plano não ser suspenso, basta realizar
        o pagamento da forma normal, assim, estará podendo utilizar a hospedagem normalmente.
        \n \nLink do Painel: https://app.realhosting.com.br \n \nIdentificador do
        Plano %s \n \nData máxima de pagamento antes de ser suspenso: %s \n \nData
        em que deve ser realizado de forma normal o pagamento, para não ocorrer avisos
        prévios: %s \n \nPara renovar seu plano utilize o comando `/renovar` \n \nAtenciosamente,
        RealHosting.'
      thumbnail: https://media.discordapp.net/attachments/856621081438453770/1027391598541164574/Dois_Laranjas.png?width=534&height=534
      site: https://app.realhosting.com.br
      fields:
        '1':
          name: Horário de Atendimento
          value: 14:30 às 23:00
          inline: true
        '2':
          name: Dias de Atendimento
          value: Segunda a Sexta (Salvo Feriados)
          inline: true
    server:
      title: ':desktop: Aqui você poderá escolher o tipo do seu servidor'
      footer: Auto-Atendimento oficial da RealHosting
      thumbnail: https://media.discordapp.net/attachments/856621081438453770/1027391598541164574/Dois_Laranjas.png?width=534&height=534
      description: Clique no tipo do servidor que você deseja fazer!
      site: https://app.realhosting.com.br
      fields:
        '1':
          name: Horário de Atendimento
          value: 14:30 às 23:00
          inline: true
        '2':
          name: Dias de Atendimento
          value: Segunda a Sexta (Salvo Feriados)
          inline: true
      type:
        '1':
          name: Paper Spigot
          value: server.type.paper_spigot
          description: Usado para criar servidores de Minecraft
          id: '1'
          emoji: U+1F9F1
        '2':
          name: BungeeCord
          value: server.type.bungeecord
          description: Usado para criar uma rede de servidores
          id: '2'
          emoji: U+1F310
        '3':
          name: PocketMine
          value: server.type.pocketmine
          description: Usado para jogar Minecraft com amigos
          id: '3'
          emoji: U+260E
        '4':
          name: Nukkit
          value: server.type.nukkit
          description: Crie um servidor com plugins
          id: '4'
          emoji: U+1F4F1
        '5':
          name: Bedrock
          value: server.type.bedrock
          description: Jogue com seus amigos com Minecraft Bedrock
          id: '5'
          emoji: U+1F5A5
        '6':
          name: Aplicação Java
          value: server.type.java_bot
          description: Hospede aplicações feitas em Java
          id: '6'
          emoji: U+2699
        '7':
          name: Aplicação NodeJS
          value: server.type.nodejs_bot
          description: Hospede aplicações feitas em NodeJS
          id: '7'
          emoji: U+1F527
    panel:
      title: ':identification_card: Auto atendimento da RealHosting'
      footer: Estamos quase terminando...
      description: Utilize o comando /painel para preencher suas informações, caso
        já tenha uma conta insira apenas o email que deseja adicionar o servidor.
      thumbnail: https://media.discordapp.net/attachments/856621081438453770/1027391598541164574/Dois_Laranjas.png?width=534&height=534
      site: https://app.realhosting.com.br
      fields:
        '1':
          name: Horário de Atendimento
          value: 14:30 às 23:00
          inline: true
        '2':
          name: Dias de Atendimento
          value: Segunda a Sexta (Salvo Feriados)
          inline: true
  payment:
    mercado-pago:
      access-token: APP_USR-3033113519295434-101615-794e93ff37f29b401ddc4cf85cfc9449-1187350395
      external-pos-id: REALCAIXA001
      user-id: 1187350395
  panel:
    url: https://app.realhosting.com.br
    token: ptla_WVBE62LrC5rbBTwUuU9XWGiQBexmf74gd7PRrZiNSze
