bot:
  guild:
    ticket-category-id: 896872221618896956
    ticket-chat-id: 896872174940463166
    ticket:
      title: Title
      footer: Footer
      text:
        - abc
        - '123'
      description: |-
        Hello World
         Zumo was here!
      fields:
        '1':
          name: My Name is
          value: Zumo
          inline: true
        '2':
          name: My Job is
          value: Supporter of RealHosting
          inline: true
